name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  prettify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # # - name: Run Python script
      # #   run: python backend/app.py

      # - name: Set PYTHONPATH
      #   run: echo "export PYTHONPATH=${PYTHONPATH}:$(pwd)/backend" >> $GITHUB_ENV

      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8 --extend-ignore=E501 --exit-zero --select=E,W,F app.py
      #     git add backend/app.py
      #     git diff-index --quiet HEAD || git commit -m "Fix linting issues [skip ci]"

      - name: Unit Test With PyTest
        run : | 
          pip install pytest
          cd backend
          pytest test_app.py
          cd ../

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kaveensp/prettify-docker
          tag: latest
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}